services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: es
    environment:
      - discovery.type=single-node
    networks: 
      - foodtrucks_network

  flask_app:
    image: flask_app
    build:
      context: .
      dockerfile: Dockerfile.multistage
    container_name: flask_app
    depends_on: 
      - elasticsearch
    ports:
      - "5000:5000"   
    networks: 
      - foodtrucks_network
      - nginx_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./templates:/usr/share/nginx/html/templates
      - ./static:/usr/share/nginx/html/static
    ports:
      - "8080:80"
    depends_on:
      - flask_app
    networks:
      - nginx_network

networks:
  foodtrucks_network:
  nginx_network:
volumes:
  static_files: